### ISSUE TITLE
Label in markets is incorrect

### ISSUE THREAD

**Issue by nelsonic** [numo-labs/lambda-taggable-geonames-indexer#25]
![geo-market-label-incorrect](https://cloud.githubusercontent.com/assets/194400/15041937/b9bbf77c-12b7-11e6-8040-0947a573d0a0.png)

https://numo-taggy.s3.amazonaws.com/ci/geo/geonames/geo%3Ageonames.6255148.json

Noted by @nikhilaravi 

Think I've spotted why this is happening:
https://github.com/numo-labs/lambda-taggable-geonames-indexer/blob/ff92e2ef7d05ab729c30fa4b4fffd2dfa0b99aaa/lib/format_tags.js#L72 `String` ...

**Comment by nelsonic** [comment]
@nikhilaravi if you get a chance, please confirm if you are still seeing this issue on Monday. 👍 😉

**Comment by nelsonic** [comment]
This was resolved in the PR: #26 
@nikhilaravi to confirm its fixed.

**Comment by nikhilaravi** [comment]
@nelsonic I think so! All the country names are coming back find in autocomplete!
